# Generated by Django 4.2.17 on 2025-01-09 12:34

import customUser.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Имя пользователя может состоять только из латинских букв, цифр и символа подчеркивания.', regex='^[a-zA-Z0-9_]+$'), customUser.models.validate_username]),
        ),
    ]
