# Generated by Django 4.2.17 on 2025-03-26 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brainstorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('completionDate', models.DateField(auto_now_add=True)),
                ('details', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_brainstorms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participated_brainstorms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
