# Generated by Django 4.2.17 on 2025-01-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstormsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brainstorm',
            old_name='completion_date',
            new_name='completionDate',
        ),
    ]
