# Generated by Django 4.2.17 on 2025-01-19 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brainstormsApp', '0003_brainstorm_isinprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brainstorm',
            name='isInProgress',
        ),
    ]
