# Generated by Django 4.2.17 on 2025-01-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roomApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[roomApp.models.validate_title])),
                ('room_code', models.CharField(default=roomApp.models.generate_room_code, max_length=6, unique=True)),
                ('details', models.TextField(blank=True)),
                ('isChatStarted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participated_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
