# Generated by Django 4.2.17 on 2025-03-26 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roomApp.models
from roomApp.models import RoomType


def fill_room_type(apps, schema_editor):
    types = ['Классический', 'Round Robin']
    RoomType.objects.create(id=1, name=types[0])
    RoomType.objects.create(id=2, name=types[1])

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idea_number', models.IntegerField()),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.RunPython(fill_room_type),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, validators=[roomApp.models.validate_title])),
                ('room_code', models.CharField(default=roomApp.models.generate_room_code, max_length=6, unique=True)),
                ('details', models.TextField(blank=True)),
                ('isChatStarted', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participated_rooms', to=settings.AUTH_USER_MODEL)),
                ('room_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='roomApp.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roomApp.idea')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='roomApp.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='idea',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='roomApp.room'),
        ),
        migrations.AddField(
            model_name='idea',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_ideas', to=settings.AUTH_USER_MODEL),
        ),
    ]
