# Generated by Django 4.2.17 on 2025-03-27 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_rounds', models.IntegerField(default=0)),
                ('received_ideas', models.IntegerField(default=0)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_data', to='roomApp.room')),
            ],
        ),
    ]
