# Generated by Django 4.2.17 on 2025-03-27 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roomApp', '0002_roundrobindata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundrobindata',
            name='room',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_data', to='roomApp.room'),
        ),
    ]
